version: "3.8"

services:
  postgres:
    container_name: fastify-application-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-application
      PGDATA: /data/postgres
    volumes:
      - polls_pg_data:/data/postgres

volumes:
  polls_pg_data:
